
export const downloadAsPDF = (title: string, content: string, source: string) => {
  // Symulacja profesjonalnego raportu DLG w formacie PDF
  // W środowisku produkcyjnym zalecane użycie jsPDF.
  const pdfHeader = `%PDF-1.4
%DLG_QUANTUM_REPORT
1 0 obj
<< /Title (${title}) /Author (GO-SERVICE.PL) /Subject (Neural Data Extraction) >>
endobj
2 0 obj
<< /Type /Catalog /Pages 3 0 R >>
endobj
3 0 obj
<< /Type /Pages /Kids [4 0 R] /Count 1 >>
endobj
4 0 obj
<< /Type /Page /Parent 3 0 R /MediaBox [0 0 612 792] /Contents 5 0 R >>
endobj
5 0 obj
<< /Length ${content.length + 1000} >>
stream
BT
/F1 18 Tf 50 720 Td (${title.replace(/[()]/g, '')}) Tj
/F2 12 Tf 0 -30 Td (Origin Enclave: ${source.replace(/[()]/g, '')}) Tj
/F2 10 Tf 0 -40 Td (--------------------------------------------------------------------------------) Tj
/F2 10 Tf 0 -20 Td (AUTOMATED NEURAL SUMMARY:) Tj
/F2 10 Tf 0 -20 Td (${content.substring(0, 100).replace(/[()]/g, '')}) Tj
/F2 10 Tf 0 -15 Td (${content.substring(100, 200).replace(/[()]/g, '')}) Tj
/F2 10 Tf 0 -15 Td (${content.substring(200, 300).replace(/[()]/g, '')}) Tj
/F2 10 Tf 0 -15 Td (${content.substring(300, 400).replace(/[()]/g, '')}) Tj
/F2 10 Tf 0 -40 Td (--------------------------------------------------------------------------------) Tj
/F2 8 Tf 0 -20 Td (Generated by go-service.pl Identity Base v4.2. Secure Channel Active.) Tj
ET
endstream
endobj
xref
0 6
0000000000 65535 f
trailer
<< /Size 6 /Root 2 0 R >>
startxref
450
%%EOF`;

  const blob = new Blob([pdfHeader], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `DLG_REPORT_${title.replace(/\s+/g, '_').toUpperCase()}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
